# This is the practice on numpy

here is a useful reference :
http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html

In [4]:
import numpy as np

# 1. Reverse a vector (first element becomes last)

In [6]:
x = np.arange(50)
              #complete here ,to reverse x
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 2. Create a 2d array with 1 on the border and 0 inside 

In [14]:
x = np.ones((10,10))
x[1:-1,1:-1]=0
                    #complete here ,to make output as following sample 
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 3. Multiply a 2x2 matrix (a) by a 2x2 matrix(b)  (real matrix product)

In [18]:
a = np.ones((2,2))
b = np.ones((2,2))
c = np.matmul(a,b)
                   #complete here ,to make output as following sample 
c

array([[2., 2.],
       [2., 2.]])

# 4. Create random vector of size 10 and replace the maximum value by 0

In [31]:
Z = np.random.random(10)
print(Z)
print(Z.argmax())
Z[Z.argmax()]=0                     #complete here ,to make output as following sample 
print(Z)

[0.93063554 0.81198424 0.9293956  0.76327973 0.0593813  0.51986616
 0.6333121  0.77985134 0.89249379 0.37983125]
0
[0.         0.81198424 0.9293956  0.76327973 0.0593813  0.51986616
 0.6333121  0.77985134 0.89249379 0.37983125]


# 5. How to find the closest value (to a given scalar) in an array? 

In [53]:
z = np.arange(10)
v = np.random.uniform(0,10)
print(z)
print(v)                
index = np.abs(v-z).argmin()                          #complete here ,to make output as following sample
print(z[index])

[0 1 2 3 4 5 6 7 8 9]
4.785668919188831
5


# 6. Create a 8x8 matrix and fill it with a checkerboard pattern

In [63]:
Z = np.zeros((8,8),dtype=int)
Z[:-1:2,:-1:2] = 1
Z[1::2,1::2] = 1                          #complete here ,to make output as following sample 

print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 7. Normalize a 5x5 random matrix 

In [135]:
Z = np.random.random((5,5))

#complete here ,to make output as following sample

print(Z)
Z = (Z-Z.min())/(Z.max()-Z.min())
print(Z)


[[0.89317277 0.21752408 0.42550834 0.66443857 0.26573413]
 [0.9345935  0.58047824 0.79963842 0.8282217  0.54413509]
 [0.8286471  0.07052149 0.9621918  0.14383761 0.42285026]
 [0.87806336 0.4766916  0.95551898 0.15704386 0.52658139]
 [0.26240223 0.52835739 0.93667218 0.4725491  0.68105187]]
[[0.92259579 0.16486204 0.39811446 0.6660725  0.21892917]
 [0.96904876 0.57191177 0.81769789 0.84975377 0.53115326]
 [0.85023085 0.         1.         0.08222334 0.39513345]
 [0.90565073 0.45551602 0.99251649 0.09703403 0.51146695]
 [0.21519247 0.51345872 0.97137998 0.45087024 0.68470417]]


# 8. Extract the integer part of a random array using 5 different methods 

In [136]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[0. 4. 6. 6. 5. 0. 6. 4. 0. 2.]
[0. 4. 6. 6. 5. 0. 6. 4. 0. 2.]
[0. 4. 6. 6. 5. 0. 6. 4. 0. 2.]
[0 4 6 6 5 0 6 4 0 2]
[0. 4. 6. 6. 5. 0. 6. 4. 0. 2.]


# 9. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [167]:
Z = np.random.random((10,2))
print(Z)
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)                          #complete here ,to make output as following sample 
T = np.arctan(Y,X)
print(R)
print(T)
Z = np.zeros((10,2))      # dirty but works
Z[:,0] = R
Z[:,1] = T
print(Z)

[[0.04323221 0.14964598]
 [0.14456253 0.6118188 ]
 [0.18623604 0.24794557]
 [0.86215762 0.72454264]
 [0.31167254 0.63045274]
 [0.56762348 0.08240815]
 [0.60298642 0.37409813]
 [0.58797266 0.72900109]
 [0.13491084 0.70517854]
 [0.35112005 0.32277531]]
[0.15576567 0.6286657  0.31009816 1.1261784  0.70328545 0.57357434
 0.70960695 0.93656523 0.71796776 0.4769373 ]
[0.1485437  0.5490645  0.24304415 0.62700834 0.56251078 0.08222236
 0.35797975 0.6299258  0.61419304 0.31221843]
[[0.15576567 0.1485437 ]
 [0.6286657  0.5490645 ]
 [0.31009816 0.24304415]
 [1.1261784  0.62700834]
 [0.70328545 0.56251078]
 [0.57357434 0.08222236]
 [0.70960695 0.35797975]
 [0.93656523 0.6299258 ]
 [0.71796776 0.61419304]
 [0.4769373  0.31221843]]


# 10. Tell the difference between view and copy, among b,c,d which is shade copy of a, which is deep copy of a?

In [82]:
#creat a
a = np.array([[1,2,3],[4,5,6]])
# b is another reference object of the array
b = a
#change b
b[0]=0
print("b:")
print(b)
print("a:")
print(a)

# c is the view on piece of a
c = a[:,1]
#change c
c += -1
print("c:")
print (c)
print("a:")
print(a)

# d is a copy of a
d = a.copy()
d -=d
print("d:")
print(d)
print("a:")
print(a)


b:
[[0 0 0]
 [4 5 6]]
a:
[[0 0 0]
 [4 5 6]]
c:
[-1  4]
a:
[[ 0 -1  0]
 [ 4  4  6]]
d:
[[0 0 0]
 [0 0 0]]
a:
[[ 0 -1  0]
 [ 4  4  6]]


Solutions: b,c is a shadow copy, and d is a deep copy. Since changes on b,c will still affect a, but changes on d won't.